/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vbuttongroup;

import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

/**
     * 1) crear botones
     * 2) arratrar group aunque momlo vemos
     * 3)Vamso a  la pantalla navigator
     * 3.1)Cambimos nombre variable 
     * 4)añadimos en constructor los RB al GRB
     * 5)Creamos evento:
     * if(RB1.isSelected()) this.LBRB.setText(RB1.getText());
     */
public class V extends javax.swing.JFrame {

    DefaultListModel  dl= new  DefaultListModel();
   String[] s = { "green", "red", "orange", "dark blue" };
    
    
    
    
    
    
    public V() {
        initComponents();
        this.GRB.add(RB1);
        this.GRB.add(RB2);
        this.GRB.add(RB3);
        initLT();
    }
    
    
    
    
    public void initLT(){
         
         for(String st:s) dl.addElement(st);
         
         this.jList1.setModel(dl);
         jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         jList1.setSelectedIndex(1);
         this.LBLista.setText(String.valueOf(jList1.getSelectedValue()));
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GRB = new javax.swing.ButtonGroup();
        RB1 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        RB3 = new javax.swing.JRadioButton();
        BTOpcion = new javax.swing.JButton();
        Lista = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        LBLista = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        LBCB = new javax.swing.JLabel();
        BTSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        RB1.setText(" rojo");
        RB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB1ActionPerformed(evt);
            }
        });

        RB2.setText("verde");

        RB3.setText("azul");

        BTOpcion.setText("Opcion");
        BTOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTOpcionActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        Lista.setViewportView(jList1);

        LBLista.setText("jLabel1");

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        BTSalir.setText("Salir");
        BTSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RB3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RB2)
                                .addGap(75, 75, 75)
                                .addComponent(BTOpcion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RB1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                                .addComponent(BTSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(38, 38, 38)
                                .addComponent(LBCB, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(LBLista)))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB1)
                    .addComponent(BTSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB2)
                    .addComponent(BTOpcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RB3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(LBLista)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(LBCB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
       
        
    }//GEN-LAST:event_formMouseClicked

    private void BTOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTOpcionActionPerformed
         if(RB1.isSelected()){ JOptionPane.showConfirmDialog(this,"rojo");}
        
        if(RB2.isSelected()){ JOptionPane.showConfirmDialog(this,"verde");}
        
        if(RB3.isSelected()) {JOptionPane.showConfirmDialog(this,"azul");}
    }//GEN-LAST:event_BTOpcionActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
       this.LBLista.setText(String.valueOf(jList1.getSelectedValue()));
    }//GEN-LAST:event_jList1MouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       if(this.jCheckBox1.isSelected()) this.LBCB.setText("selecionado");
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void BTSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSalirActionPerformed
                System.exit(0);      // TODO add your handling code here:
    }//GEN-LAST:event_BTSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTOpcion;
    private javax.swing.JButton BTSalir;
    private javax.swing.ButtonGroup GRB;
    private javax.swing.JLabel LBCB;
    private javax.swing.JLabel LBLista;
    private javax.swing.JScrollPane Lista;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JRadioButton RB3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JList jList1;
    // End of variables declaration//GEN-END:variables
}
